-- MySQL Script generated by MySQL Workbench
-- sáb 03 fev 2024 23:55:38
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema smartchurch
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `smartchurch` ;

-- -----------------------------------------------------
-- Schema smartchurch
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `smartchurch` DEFAULT CHARACTER SET utf8 ;
USE `smartchurch` ;

-- -----------------------------------------------------
-- Table `smartchurch`.`agendas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`agendas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`agendas` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `logo` VARCHAR(256) NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `responsavel` CHAR(24) NULL DEFAULT NULL COMMENT 'id do responsavel',
  `time_ini` DATETIME NULL DEFAULT NULL,
  `time_end` DATETIME NULL DEFAULT NULL,
  `observacoes` TEXT NULL DEFAULT NULL COMMENT 'detalhe, observacoes do local, como numero da sala, etc',
  `recorrente` CHAR(1) NULL DEFAULT NULL COMMENT 'se repete ou nao, como cultos, ebd, etc',
  `dias_horarios` TEXT NULL DEFAULT NULL COMMENT 'json de configuracao de dias e horarios se recorrente',
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'agendas';


-- -----------------------------------------------------
-- Table `smartchurch`.`perfis`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`perfis` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`perfis` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `descricao` VARCHAR(256) NULL DEFAULT NULL,
  `staff_only` CHAR(1) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`usuarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`usuarios` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`usuarios` (
  `id` CHAR(24) NOT NULL,
  `perfil` CHAR(24) NULL DEFAULT NULL,
  `nome` VARCHAR(150) NOT NULL,
  `email` VARCHAR(256) NULL DEFAULT NULL,
  `senha` CHAR(40) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL COMMENT 'ativo, bloqueado',
  `tp` CHAR(3) NULL DEFAULT NULL COMMENT 'staff, admin, igreja',
  `avatar` VARCHAR(256) NULL DEFAULT NULL,
  `is_master` CHAR(1) NULL DEFAULT NULL,
  `is_android` CHAR(1) NULL DEFAULT NULL,
  `fcm_token` TEXT NULL DEFAULT NULL,
  `reset_code` VARCHAR(7) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_sync` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usuarios_perfis1_idx` (`perfil` ASC) VISIBLE,
  CONSTRAINT `fk_usuarios_perfis1`
    FOREIGN KEY (`perfil`)
    REFERENCES `smartchurch`.`perfis` (`id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`profissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`profissoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`profissoes` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`pessoas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`pessoas` (
  `id` CHAR(24) NOT NULL,
  `profissao` CHAR(24) NULL,
  `sexo` CHAR(1) NULL DEFAULT NULL,
  `data_nascimento` DATE NULL DEFAULT NULL,
  `crianca` CHAR(1) NULL,
  `responsavel` CHAR(24) NULL,
  `estado_civil` CHAR(3) NULL DEFAULT NULL,
  `tem_filhos` CHAR(1) NULL DEFAULT NULL,
  `escolaridade` CHAR(3) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `celular_1` VARCHAR(20) NULL DEFAULT NULL,
  `celular_2` VARCHAR(20) NULL DEFAULT NULL,
  `pai` VARCHAR(150) NULL,
  `mae` VARCHAR(150) NULL,
  `naturalidade` VARCHAR(256) NULL,
  `nacionalidade` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoas_profissoes1_idx` (`profissao` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_usuarios1`
    FOREIGN KEY (`id`)
    REFERENCES `smartchurch`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pessoas_profissoes1`
    FOREIGN KEY (`profissao`)
    REFERENCES `smartchurch`.`profissoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`supremo_concilio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`supremo_concilio` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`supremo_concilio` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL,
  `fundacao` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`sinodos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`sinodos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`sinodos` (
  `id` CHAR(24) NOT NULL,
  `nacional` CHAR(24) NOT NULL,
  `sigla` VARCHAR(15) NULL DEFAULT NULL,
  `nome` VARCHAR(256) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL,
  `fundacao` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sinodos_supremo_conciclio1_idx` (`nacional` ASC) VISIBLE,
  CONSTRAINT `fk_sinodos_supremo_conciclio1`
    FOREIGN KEY (`nacional`)
    REFERENCES `smartchurch`.`supremo_concilio` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`presbiterios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`presbiterios` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`presbiterios` (
  `id` CHAR(24) NOT NULL,
  `sinodo` CHAR(24) NOT NULL,
  `sigla` VARCHAR(15) NULL DEFAULT NULL,
  `nome` VARCHAR(256) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL,
  `fundacao` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_presbiterios_sinodos1_idx` (`sinodo` ASC) VISIBLE,
  CONSTRAINT `fk_presbiterios_sinodos1`
    FOREIGN KEY (`sinodo`)
    REFERENCES `smartchurch`.`sinodos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`igrejas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`igrejas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`igrejas` (
  `id` CHAR(24) NOT NULL,
  `sinodo` CHAR(24) NULL DEFAULT NULL,
  `presbiterio` CHAR(24) NULL DEFAULT NULL,
  `igreja` CHAR(24) NULL DEFAULT NULL COMMENT 'referencia para outra igreja no caso de congregacao, ponto de pregacao',
  `nome` VARCHAR(256) NULL DEFAULT NULL,
  `fundacao` DATE NULL DEFAULT NULL,
  `organizada` CHAR(1) NULL DEFAULT NULL COMMENT 'organizada, congregacao, ponto',
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_igrejas_presbiterios1_idx` (`presbiterio` ASC) VISIBLE,
  INDEX `fk_igrejas_sinodos1_idx` (`sinodo` ASC) VISIBLE,
  CONSTRAINT `fk_igrejas_presbiterios1`
    FOREIGN KEY (`presbiterio`)
    REFERENCES `smartchurch`.`presbiterios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_igrejas_sinodos1`
    FOREIGN KEY (`sinodo`)
    REFERENCES `smartchurch`.`sinodos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`salas_ebd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`salas_ebd` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`salas_ebd` (
  `id` CHAR(24) NOT NULL,
  `igreja` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `inicio` DATE NULL DEFAULT NULL COMMENT 'inicio da sala',
  `fim` DATE NULL DEFAULT NULL COMMENT 'termino da sala',
  `atualizar_sumario` CHAR(1) NULL COMMENT 'flag pra indicar se o sumario deve ser atualizado',
  `last_sumario_run` DATETIME NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salas_ebd_igrejas1_idx` (`igreja` ASC) VISIBLE,
  CONSTRAINT `fk_salas_ebd_igrejas1`
    FOREIGN KEY (`igreja`)
    REFERENCES `smartchurch`.`igrejas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'salas da escola dominical';


-- -----------------------------------------------------
-- Table `smartchurch`.`alunos_das_salas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`alunos_das_salas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`alunos_das_salas` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `sala` CHAR(24) NOT NULL,
  `inicio` DATE NULL DEFAULT NULL COMMENT 'data em que o aluno foi aidicionado a sala e passa a contar frequencia',
  `fim` DATE NULL,
  `stat` CHAR(3) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pessoas_has_salas_ebd_salas_ebd1_idx` (`sala` ASC) VISIBLE,
  INDEX `fk_pessoas_has_salas_ebd_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_has_salas_ebd_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pessoas_has_salas_ebd_salas_ebd1`
    FOREIGN KEY (`sala`)
    REFERENCES `smartchurch`.`salas_ebd` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`atas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`atas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`atas` (
  `id` CHAR(24) NOT NULL,
  `titulo` VARCHAR(256) NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `conteudo` MEDIUMTEXT NULL DEFAULT NULL,
  `arquivo` VARCHAR(256) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `requer_aprovacao` CHAR(1) NULL,
  `aprovado` CHAR(1) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL COMMENT 'ata aprovada ou nao',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`aprovacoes_ata`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`aprovacoes_ata` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`aprovacoes_ata` (
  `id` CHAR(24) NOT NULL,
  `ata` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `aprovado` CHAR(1) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_aprovacoes_atas1_idx` (`ata` ASC) VISIBLE,
  INDEX `fk_aprovacoes_ata_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_aprovacoes_ata_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_aprovacoes_atas1`
    FOREIGN KEY (`ata`)
    REFERENCES `smartchurch`.`atas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'aprovacoes de ata, caso seja necessario';


-- -----------------------------------------------------
-- Table `smartchurch`.`eleicoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`eleicoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`eleicoes` (
  `id` CHAR(24) NOT NULL,
  `agenda` CHAR(24) NULL DEFAULT NULL,
  `evento` CHAR(24) NULL DEFAULT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `time_ini` DATETIME NULL DEFAULT NULL COMMENT 'caso de eleicao online, quando comeca',
  `time_end` DATETIME NULL DEFAULT NULL COMMENT 'caso de eleicao online, quando termina',
  `apenas_presentes` CHAR(1) NULL DEFAULT NULL,
  `apenas_delegados` CHAR(1) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`cargo` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`cargo` (
  `id` CHAR(24) NOT NULL,
  `perfil` CHAR(24) NULL DEFAULT NULL COMMENT 'perfil de permissoes do cargo',
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `instancia` CHAR(3) NULL DEFAULT NULL COMMENT 'instancias que tem esse cargo, como sociedades, secretaria, ministerio, presbiterio, etc',
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cargo_perfis1_idx` (`perfil` ASC) VISIBLE,
  CONSTRAINT `fk_cargo_perfis1`
    FOREIGN KEY (`perfil`)
    REFERENCES `smartchurch`.`perfis` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`votacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`votacoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`votacoes` (
  `id` CHAR(24) NOT NULL,
  `cargo` CHAR(24) NOT NULL,
  `eleicao` CHAR(24) NOT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_votacoes_cargo1_idx` (`cargo` ASC) VISIBLE,
  INDEX `fk_votacoes_eleicoes1_idx` (`eleicao` ASC) VISIBLE,
  CONSTRAINT `fk_votacoes_cargo1`
    FOREIGN KEY (`cargo`)
    REFERENCES `smartchurch`.`cargo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_votacoes_eleicoes1`
    FOREIGN KEY (`eleicao`)
    REFERENCES `smartchurch`.`eleicoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`escrutinios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`escrutinios` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`escrutinios` (
  `id` CHAR(24) NOT NULL,
  `votacao` CHAR(24) NOT NULL,
  `escrutinio` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_escrutinios_votacoes1_idx` (`votacao` ASC) VISIBLE,
  CONSTRAINT `fk_escrutinios_votacoes1`
    FOREIGN KEY (`votacao`)
    REFERENCES `smartchurch`.`votacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`candidatos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`candidatos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`candidatos` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `eleicao` CHAR(24) NOT NULL,
  `votacao` CHAR(24) NOT NULL,
  `escrutinio` CHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_candidatos_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  INDEX `fk_candidatos_eleicoes1_idx` (`eleicao` ASC) VISIBLE,
  INDEX `fk_candidatos_votacoes1_idx` (`votacao` ASC) VISIBLE,
  INDEX `fk_candidatos_escrutinios1_idx` (`escrutinio` ASC) VISIBLE,
  CONSTRAINT `fk_candidatos_eleicoes1`
    FOREIGN KEY (`eleicao`)
    REFERENCES `smartchurch`.`eleicoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidatos_escrutinios1`
    FOREIGN KEY (`escrutinio`)
    REFERENCES `smartchurch`.`escrutinios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidatos_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_candidatos_votacoes1`
    FOREIGN KEY (`votacao`)
    REFERENCES `smartchurch`.`votacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`categorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`categorias` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`categorias` (
  `id` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `cor` VARCHAR(45) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`checkins`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`checkins` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`checkins` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `ref` CHAR(35) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_checkins_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_checkins_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'checkin em evento, atividade, etc. Usado para verificar presenca em eventos que fazem contagem de presenca como congressos';


-- -----------------------------------------------------
-- Table `smartchurch`.`ufs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`ufs` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`ufs` (
  `id` INT NOT NULL COMMENT 'id no ibge',
  `nome` VARCHAR(256) NULL DEFAULT NULL,
  `sigla` CHAR(2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela backup das ufs listadas no servico do ibge';


-- -----------------------------------------------------
-- Table `smartchurch`.`cidades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`cidades` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`cidades` (
  `id` INT NOT NULL COMMENT 'id no igbe',
  `uf` INT NOT NULL,
  `nome` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cidades_ufs1_idx` (`uf` ASC) VISIBLE,
  CONSTRAINT `fk_cidades_ufs1`
    FOREIGN KEY (`uf`)
    REFERENCES `smartchurch`.`ufs` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela backup das cidades listadas no servico do ibge';


-- -----------------------------------------------------
-- Table `smartchurch`.`comissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`comissoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`comissoes` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'comissoes em eventos como congressos, etc';


-- -----------------------------------------------------
-- Table `smartchurch`.`comissoes_executivas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`comissoes_executivas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`comissoes_executivas` (
  `id` CHAR(24) NOT NULL,
  `gestao_inicio` DATE NULL DEFAULT NULL,
  `gestao_fim` DATE NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'comissoes executivas de presbiterios, federacoes, etc';


-- -----------------------------------------------------
-- Table `smartchurch`.`configs_pagto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`configs_pagto` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`configs_pagto` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL DEFAULT NULL,
  `token_prod` VARCHAR(45) NULL DEFAULT NULL,
  `token_test` VARCHAR(45) NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL COMMENT 'evento, igreja, sociedade, presbiterio, etc',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'configuracoes de pagamento, como as do pagseguro, boletofacil, etc';


-- -----------------------------------------------------
-- Table `smartchurch`.`contas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`contas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`contas` (
  `id` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`instancias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`instancias` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`instancias` (
  `id` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `modulos` TEXT NULL DEFAULT NULL,
  `pai` CHAR(24) NULL DEFAULT NULL COMMENT 'instancia pai, caso de sociedade interna, secretarias, etc',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'armazena a configuracao de modulos das instancias, clientes pagos';


-- -----------------------------------------------------
-- Table `smartchurch`.`contextos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`contextos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`contextos` (
  `id` CHAR(24) NOT NULL,
  `usuario` CHAR(24) NOT NULL,
  `instancia` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `perfil` CHAR(24) NULL DEFAULT NULL COMMENT 'perfil de permissoes aplicaveis ao contexto',
  `stat` CHAR(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_contextos_usuarios1_idx` (`usuario` ASC) VISIBLE,
  INDEX `fk_contextos_instancias1_idx` (`instancia` ASC) VISIBLE,
  CONSTRAINT `fk_contextos_instancias1`
    FOREIGN KEY (`instancia`)
    REFERENCES `smartchurch`.`instancias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contextos_usuarios1`
    FOREIGN KEY (`usuario`)
    REFERENCES `smartchurch`.`usuarios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela para indicar os contextos em que o usuario possui acesso ';


-- -----------------------------------------------------
-- Table `smartchurch`.`diretorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`diretorias` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`diretorias` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `gestao_inicio` DATE NULL DEFAULT NULL,
  `gestao_fim` DATE NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'diretorias de sociedade interna, ministerio, conselho, presbiterio, sinodo, supremo';


-- -----------------------------------------------------
-- Table `smartchurch`.`membros`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`membros` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`membros` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `igreja` CHAR(24) NOT NULL,
  `codigo` CHAR(5) NULL DEFAULT NULL COMMENT 'codigo do membro na igreja',
  `comungante` CHAR(1) NULL DEFAULT NULL COMMENT 'professo, batizado, participante',
  `especial` CHAR(1) NULL DEFAULT NULL COMMENT 'membro acamado, idoso, que requer visita pastoral, ceia em casa, etc',
  `arrolado` CHAR(1) NULL DEFAULT NULL COMMENT 'indica se o membro ja foi arroaldo ou nao',
  `data_admissao` DATE NULL DEFAULT NULL,
  `data_demissao` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL COMMENT 'ativo, nao ativo',
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_membros_igrejas1_idx` (`igreja` ASC) VISIBLE,
  INDEX `fk_membros_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_membros_igrejas1`
    FOREIGN KEY (`igreja`)
    REFERENCES `smartchurch`.`igrejas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_membros_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'membresia em igreja';


-- -----------------------------------------------------
-- Table `smartchurch`.`dizimos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`dizimos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`dizimos` (
  `id` CHAR(24) NOT NULL,
  `membro` CHAR(24) NOT NULL,
  `igreja` CHAR(24) NOT NULL,
  `data` DATE NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dizimos_igrejas1_idx` (`igreja` ASC) VISIBLE,
  INDEX `fk_dizimos_membros1_idx` (`membro` ASC) VISIBLE,
  CONSTRAINT `fk_dizimos_igrejas1`
    FOREIGN KEY (`igreja`)
    REFERENCES `smartchurch`.`igrejas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_dizimos_membros1`
    FOREIGN KEY (`membro`)
    REFERENCES `smartchurch`.`membros` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'tabela de registro de dizimos';


-- -----------------------------------------------------
-- Table `smartchurch`.`eleitores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`eleitores` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`eleitores` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `eleicao` CHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_eleitores_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  INDEX `fk_eleitores_eleicoes1_idx` (`eleicao` ASC) VISIBLE,
  CONSTRAINT `fk_eleitores_eleicoes1`
    FOREIGN KEY (`eleicao`)
    REFERENCES `smartchurch`.`eleicoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_eleitores_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`enderecos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`enderecos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`enderecos` (
  `id` CHAR(24) NOT NULL,
  `endereco` VARCHAR(256) NULL DEFAULT NULL,
  `numero` VARCHAR(20) NULL DEFAULT NULL,
  `complemento` VARCHAR(45) NULL DEFAULT NULL,
  `bairro` VARCHAR(150) NULL DEFAULT NULL,
  `cidade` VARCHAR(256) NULL DEFAULT NULL,
  `uf` CHAR(2) NULL DEFAULT NULL,
  `cep` VARCHAR(20) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'enderecos de igrejas, pessoas, atividades, eventos, etc';


-- -----------------------------------------------------
-- Table `smartchurch`.`subcategorias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`subcategorias` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`subcategorias` (
  `id` CHAR(24) NOT NULL,
  `categoria` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `cor` VARCHAR(45) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subcategorias_categorias1_idx` (`categoria` ASC) VISIBLE,
  CONSTRAINT `fk_subcategorias_categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `smartchurch`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`entradas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`entradas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`entradas` (
  `id` CHAR(24) NOT NULL,
  `categoria` CHAR(24) NULL DEFAULT NULL,
  `subcategoria` CHAR(24) NULL DEFAULT NULL,
  `conta` CHAR(24) NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `registro` VARCHAR(150) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_registro` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL COMMENT 'dizimo, oferta, doacao, receita, outros',
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_entradas_contas1_idx` (`conta` ASC) VISIBLE,
  INDEX `fk_entradas_subcategorias1_idx` (`subcategoria` ASC) VISIBLE,
  INDEX `fk_entradas_categorias1_idx` (`categoria` ASC) VISIBLE,
  CONSTRAINT `fk_entradas_categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `smartchurch`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entradas_contas1`
    FOREIGN KEY (`conta`)
    REFERENCES `smartchurch`.`contas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entradas_subcategorias1`
    FOREIGN KEY (`subcategoria`)
    REFERENCES `smartchurch`.`subcategorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`series_estudos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`series_estudos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`series_estudos` (
  `id` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `chave` VARCHAR(256) NULL DEFAULT NULL,
  `logo` VARCHAR(256) NULL DEFAULT NULL,
  `destinatarios` TEXT NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`estudos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`estudos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`estudos` (
  `id` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `serie` CHAR(24) NULL DEFAULT NULL,
  `autor` CHAR(24) NULL DEFAULT NULL,
  `titulo` VARCHAR(150) NULL DEFAULT NULL,
  `chave` VARCHAR(256) NULL DEFAULT NULL,
  `logo` VARCHAR(256) NULL DEFAULT NULL,
  `logo_app` VARCHAR(256) NULL,
  `conteudo` TEXT NULL DEFAULT NULL,
  `anexo` VARCHAR(256) NULL DEFAULT NULL,
  `video` VARCHAR(256) NULL DEFAULT NULL,
  `audio` TEXT NULL DEFAULT NULL,
  `destinatarios` TEXT NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `autor_indx` USING BTREE (`autor`) VISIBLE,
  INDEX `fk_estudos_series_estudos1_idx` (`serie` ASC) VISIBLE,
  CONSTRAINT `fk_estudos_series_estudos1`
    FOREIGN KEY (`serie`)
    REFERENCES `smartchurch`.`series_estudos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`eventos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`eventos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`eventos` (
  `id` CHAR(24) NOT NULL,
  `agenda` CHAR(24) NULL DEFAULT NULL COMMENT 'referencia a informacao na agenda',
  `chave` CHAR(40) NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `logo` VARCHAR(256) NULL DEFAULT NULL,
  `descricao` TEXT NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `inscricoes_ativas` CHAR(1) NULL DEFAULT NULL,
  `formulario_inscricao` TEXT NULL DEFAULT NULL COMMENT 'json de configuracao do formulario de inscricao',
  `valor` DECIMAL(10,2) NULL DEFAULT NULL COMMENT 'valor total sem desconto ou lote',
  `opcoes_pagto` TEXT NULL DEFAULT NULL COMMENT 'json com as opcoes de pagamento',
  `lotes` TEXT NULL DEFAULT NULL COMMENT 'json configurando os lotes de inscricao: datas e valores de cada lote',
  `fim_inscricao` DATETIME NULL DEFAULT NULL COMMENT 'data e hora de termino das inscricoes se existir',
  `time_ini` DATETIME NULL DEFAULT NULL,
  `time_end` DATETIME NULL DEFAULT NULL,
  `tem_eleicoes` CHAR(1) NULL COMMENT 'marca se o evento tem ou nao eleicoes',
  `credencial_digital` CHAR(1) NULL COMMENT 'marca se o evento usa ou não credencial digital',
  `data_delegados` DATETIME NULL COMMENT 'data limite para delegados em caso de evento com eleicao',
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'congressos, encontros, acampamentos, etc. Atividades que demandam inscricao';


-- -----------------------------------------------------
-- Table `smartchurch`.`familias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`familias` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`familias` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `parente` CHAR(24) NULL DEFAULT NULL COMMENT 'id da pessoa com a qual tem relacao familiar',
  `tipo` CHAR(3) NULL DEFAULT NULL COMMENT 'pai, mae, filho, irmao',
  `nome_externo` VARCHAR(150) NULL COMMENT 'nome do parente caso ele nao seja uma crianca e nao exista no sistema, como conjuges',
  PRIMARY KEY (`id`),
  INDEX `fk_familias_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_familias_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'relacoes familiares entre pessoas';


-- -----------------------------------------------------
-- Table `smartchurch`.`nacionais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`nacionais` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`nacionais` (
  `id` CHAR(24) NOT NULL,
  `supremo_conciclio` CHAR(24) NOT NULL,
  `reference` CHAR(3) NULL DEFAULT NULL,
  `sigla` VARCHAR(15) NULL DEFAULT NULL,
  `nome` VARCHAR(256) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL,
  `fundacao` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL COMMENT 'ump, saf, etc',
  PRIMARY KEY (`id`),
  INDEX `fk_nacionais_supremo_conciclio1_idx` (`supremo_conciclio` ASC) VISIBLE,
  CONSTRAINT `fk_nacionais_supremo_conciclio1`
    FOREIGN KEY (`supremo_conciclio`)
    REFERENCES `smartchurch`.`supremo_concilio` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`sinodais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`sinodais` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`sinodais` (
  `id` CHAR(24) NOT NULL,
  `sinodo` CHAR(24) NOT NULL,
  `nacional` CHAR(24) NOT NULL,
  `reference` CHAR(3) NULL DEFAULT NULL COMMENT 'referencia para a sociedade: ump, saf, upa, etc',
  `sigla` VARCHAR(15) NULL DEFAULT NULL,
  `nome` VARCHAR(256) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL,
  `fundacao` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sinodais_sinodos1_idx` (`sinodo` ASC) VISIBLE,
  INDEX `fk_sinodais_nacionais1_idx` (`nacional` ASC) VISIBLE,
  CONSTRAINT `fk_sinodais_nacionais1`
    FOREIGN KEY (`nacional`)
    REFERENCES `smartchurch`.`nacionais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sinodais_sinodos1`
    FOREIGN KEY (`sinodo`)
    REFERENCES `smartchurch`.`sinodos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`federacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`federacoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`federacoes` (
  `id` CHAR(24) NOT NULL,
  `sinodo` CHAR(24) NOT NULL,
  `presbiterio` CHAR(24) NOT NULL,
  `sinodal` CHAR(24) NOT NULL,
  `reference` CHAR(3) NULL DEFAULT NULL COMMENT 'ump, saf, etc',
  `sigla` VARCHAR(15) NULL DEFAULT NULL,
  `nome` VARCHAR(256) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL,
  `fundacao` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_federacoes_presbiterios1_idx` (`presbiterio` ASC) VISIBLE,
  INDEX `fk_federacoes_sinodais1_idx` (`sinodal` ASC) VISIBLE,
  INDEX `fk_federacoes_sinodos1_idx` (`sinodo` ASC) VISIBLE,
  CONSTRAINT `fk_federacoes_presbiterios1`
    FOREIGN KEY (`presbiterio`)
    REFERENCES `smartchurch`.`presbiterios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_federacoes_sinodais1`
    FOREIGN KEY (`sinodal`)
    REFERENCES `smartchurch`.`sinodais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_federacoes_sinodos1`
    FOREIGN KEY (`sinodo`)
    REFERENCES `smartchurch`.`sinodos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`freq_sumarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`freq_sumarios` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`freq_sumarios` (
  `id` CHAR(24) NOT NULL,
  `sala` CHAR(24) NOT NULL,
  `dia` DATE NULL DEFAULT NULL,
  `presentes` INT NULL DEFAULT NULL,
  `ausentes` INT NULL DEFAULT NULL,
  `visitantes` INT NULL DEFAULT NULL,
  `total` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_freq_sumarios_salas_ebd1_idx` (`sala` ASC) VISIBLE,
  CONSTRAINT `fk_freq_sumarios_salas_ebd1`
    FOREIGN KEY (`sala`)
    REFERENCES `smartchurch`.`salas_ebd` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'sumarios resumidos de frequencia por sala, visto que nem todos os presentes podem estar cadastrados no sistema';


-- -----------------------------------------------------
-- Table `smartchurch`.`frequencias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`frequencias` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`frequencias` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `sala` CHAR(24) NOT NULL,
  `presente` CHAR(1) NULL DEFAULT NULL,
  `dia` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_frequencias_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  INDEX `fk_frequencias_salas_ebd1_idx` (`sala` ASC) VISIBLE,
  CONSTRAINT `fk_frequencias_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_frequencias_salas_ebd1`
    FOREIGN KEY (`sala`)
    REFERENCES `smartchurch`.`salas_ebd` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'frequencias nas salas da ebd';


-- -----------------------------------------------------
-- Table `smartchurch`.`motivos_recusa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`motivos_recusa` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`motivos_recusa` (
  `id` CHAR(24) NOT NULL,
  `motivo` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`credenciais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`credenciais` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`credenciais` (
  `id` CHAR(24) NOT NULL,
  `id_responsavel` CHAR(24) NULL,
  `nome_responsavel` VARCHAR(150) NULL,
  `email_responsavel` VARCHAR(256) NULL,
  `telefone_responsavel` VARCHAR(20) NULL,
  `assinatura_inscrito` VARCHAR(256) NULL,
  `assinatura_responsavel` VARCHAR(256) NULL,
  `assinatura_instancia` VARCHAR(256) NULL,
  `assinatura_plataforma` VARCHAR(256) NULL,
  `stat` CHAR(3) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_credenciais_pessoas1_idx` (`id_responsavel` ASC) VISIBLE,
  CONSTRAINT `fk_credenciais_pessoas1`
    FOREIGN KEY (`id_responsavel`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`inscricoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`inscricoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`inscricoes` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `evento` CHAR(24) NOT NULL,
  `credencial_digital` CHAR(24) NULL,
  `motivo_recusa` CHAR(24) NULL,
  `igreja` CHAR(24) NULL,
  `presbiterio` CHAR(24) NULL,
  `sinodo` CHAR(24) NULL,
  `sociedade` CHAR(24) NULL DEFAULT NULL,
  `federacao` CHAR(24) NULL DEFAULT NULL,
  `sinodal` CHAR(24) NULL DEFAULT NULL,
  `qrcode` VARCHAR(15) NULL DEFAULT NULL COMMENT 'codigo do qrcode',
  `delegado` CHAR(1) NULL DEFAULT NULL COMMENT 'delegado, caso de congressos, etc',
  `cargo_ref` CHAR(3) NULL DEFAULT NULL COMMENT 'instancia de referencia do cargp',
  `cargo` CHAR(24) NULL DEFAULT NULL,
  `credencial` VARCHAR(256) NULL DEFAULT NULL COMMENT 'arquivo de credencial',
  `stat` CHAR(3) NULL DEFAULT NULL,
  `forma_pagto` CHAR(3) NULL DEFAULT NULL COMMENT 'transferencia, pagseguro, boleto, etc',
  `stat_pagto` CHAR(3) NULL DEFAULT NULL,
  `valor_pago` DECIMAL(10,2) NULL DEFAULT NULL,
  `gateway_code` VARCHAR(45) NULL DEFAULT NULL COMMENT 'codigo do gateway, como codigo do pagseguro',
  `data_pagto` DATE NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_inscricoes_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  INDEX `fk_inscricoes_eventos1_idx` (`evento` ASC) VISIBLE,
  INDEX `fk_inscricoes_motivos_recusa1_idx` (`motivo_recusa` ASC) VISIBLE,
  INDEX `fk_inscricoes_credenciais1_idx` (`credencial_digital` ASC) VISIBLE,
  CONSTRAINT `fk_inscricoes_eventos1`
    FOREIGN KEY (`evento`)
    REFERENCES `smartchurch`.`eventos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricoes_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inscricoes_motivos_recusa1`
    FOREIGN KEY (`motivo_recusa`)
    REFERENCES `smartchurch`.`motivos_recusa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inscricoes_credenciais1`
    FOREIGN KEY (`credencial_digital`)
    REFERENCES `smartchurch`.`credenciais` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`ministerios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`ministerios` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`ministerios` (
  `id` CHAR(24) NOT NULL,
  `igreja` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `logo` VARCHAR(256) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `ramal` VARCHAR(20) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_ministerios_igrejas1_idx` (`igreja` ASC) VISIBLE,
  CONSTRAINT `fk_ministerios_igrejas1`
    FOREIGN KEY (`igreja`)
    REFERENCES `smartchurch`.`igrejas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`oficiais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`oficiais` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`oficiais` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `cargo` CHAR(24) NULL DEFAULT NULL,
  `diretoria` CHAR(24) NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL DEFAULT NULL COMMENT 'email do oficial no cargo',
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  `inicio` DATE NULL DEFAULT NULL COMMENT 'inicio do oficialato',
  `fim` DATE NULL DEFAULT NULL COMMENT 'termino do oficiliato',
  `ref` CHAR(24) NULL DEFAULT NULL COMMENT 'id da instancia',
  `ref_tp` CHAR(3) NULL DEFAULT NULL COMMENT 'igreja, sociedade, ministerio, presbiterio, etc',
  `stat` CHAR(3) NULL DEFAULT NULL COMMENT 'ativo, nao ativo',
  `tipo` CHAR(3) NULL DEFAULT NULL COMMENT 'pastor, evangelista, presbitero, etc',
  `disponibilidade` CHAR(3) NULL DEFAULT NULL COMMENT 'ativo, em disponibilidade, jubilado',
  `time_cad` DATETIME NULL DEFAULT NULL COMMENT 'pastor, presbitero, diacono, etc',
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_oficiais_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  INDEX `fk_oficiais_cargo1_idx` (`cargo` ASC) VISIBLE,
  INDEX `fk_oficiais_diretorias1_idx` (`diretoria` ASC) VISIBLE,
  CONSTRAINT `fk_oficiais_cargo1`
    FOREIGN KEY (`cargo`)
    REFERENCES `smartchurch`.`cargo` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_oficiais_diretorias1`
    FOREIGN KEY (`diretoria`)
    REFERENCES `smartchurch`.`diretorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_oficiais_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'oficiais de igrejas, ministerios, presbiterios, etc';


-- -----------------------------------------------------
-- Table `smartchurch`.`pequenos_grupos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`pequenos_grupos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`pequenos_grupos` (
  `id` CHAR(24) NOT NULL,
  `igreja` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `reunioes` TEXT NULL DEFAULT NULL COMMENT 'json com os dias e horarios de reuniao',
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pequenos_grupos_igrejas1_idx` (`igreja` ASC) VISIBLE,
  CONSTRAINT `fk_pequenos_grupos_igrejas1`
    FOREIGN KEY (`igreja`)
    REFERENCES `smartchurch`.`igrejas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`participantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`participantes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`participantes` (
  `id` CHAR(24) NOT NULL,
  `grupo` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `stat` CHAR(3) NULL,
  `lider` CHAR(1) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_participantes_pequenos_grupos1_idx` (`grupo` ASC) VISIBLE,
  INDEX `fk_participantes_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_participantes_pequenos_grupos1`
    FOREIGN KEY (`grupo`)
    REFERENCES `smartchurch`.`pequenos_grupos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_participantes_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`permissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`permissoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`permissoes` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `descricao` VARCHAR(256) NULL DEFAULT NULL,
  `ordem` INT NULL DEFAULT NULL,
  `staff_only` CHAR(1) NULL DEFAULT NULL,
  `modulo` VARCHAR(45) NULL DEFAULT NULL,
  `grupo` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`permissoes_do_perfil`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`permissoes_do_perfil` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`permissoes_do_perfil` (
  `permissao` CHAR(24) NOT NULL,
  `perfil` CHAR(24) NOT NULL,
  PRIMARY KEY (`permissao`, `perfil`),
  INDEX `fk_permissoes_has_perfis_perfis1_idx` (`perfil` ASC) VISIBLE,
  INDEX `fk_permissoes_has_perfis_permissoes_idx` (`permissao` ASC) VISIBLE,
  CONSTRAINT `fk_permissoes_has_perfis_perfis1`
    FOREIGN KEY (`perfil`)
    REFERENCES `smartchurch`.`perfis` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_permissoes_has_perfis_permissoes`
    FOREIGN KEY (`permissao`)
    REFERENCES `smartchurch`.`permissoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`pessoas_das_ces`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`pessoas_das_ces` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`pessoas_das_ces` (
  `pessoa` CHAR(24) NOT NULL,
  `comissao_executiva` CHAR(24) NOT NULL,
  PRIMARY KEY (`pessoa`, `comissao_executiva`),
  INDEX `fk_pessoas_has_comissoes_executivas_comissoes_executivas1_idx` (`comissao_executiva` ASC) VISIBLE,
  INDEX `fk_pessoas_has_comissoes_executivas_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_has_comissoes_executivas_comissoes_executivas1`
    FOREIGN KEY (`comissao_executiva`)
    REFERENCES `smartchurch`.`comissoes_executivas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pessoas_has_comissoes_executivas_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`pessoas_das_comissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`pessoas_das_comissoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`pessoas_das_comissoes` (
  `pessoa` CHAR(24) NOT NULL,
  `comissao` CHAR(24) NOT NULL,
  `relator` CHAR(1) NULL DEFAULT NULL,
  PRIMARY KEY (`pessoa`, `comissao`),
  INDEX `fk_pessoas_has_comissoes_comissoes1_idx` (`comissao` ASC) VISIBLE,
  INDEX `fk_pessoas_has_comissoes_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_pessoas_has_comissoes_comissoes1`
    FOREIGN KEY (`comissao`)
    REFERENCES `smartchurch`.`comissoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_pessoas_has_comissoes_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`professores_das_salas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`professores_das_salas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`professores_das_salas` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `sala` CHAR(24) NOT NULL,
  `inicio` DATE NULL,
  `fim` DATE NULL,
  `stat` CHAR(3) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_salas_ebd_has_pessoas_salas_ebd1_idx` (`sala` ASC) VISIBLE,
  INDEX `fk_professores_das_salas_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_professores_sala`
    FOREIGN KEY (`sala`)
    REFERENCES `smartchurch`.`salas_ebd` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_professores_pessoa`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`saidas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`saidas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`saidas` (
  `id` CHAR(24) NOT NULL,
  `categoria` CHAR(24) NULL DEFAULT NULL,
  `subcategoria` CHAR(24) NULL DEFAULT NULL,
  `conta` CHAR(24) NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `registro` VARCHAR(150) NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NULL DEFAULT NULL,
  `data_registro` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL COMMENT 'pago ou nao',
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_saidas_contas1_idx` (`conta` ASC) VISIBLE,
  INDEX `fk_saidas_subcategorias1_idx` (`subcategoria` ASC) VISIBLE,
  INDEX `fk_saidas_categorias1_idx` (`categoria` ASC) VISIBLE,
  CONSTRAINT `fk_saidas_categorias1`
    FOREIGN KEY (`categoria`)
    REFERENCES `smartchurch`.`categorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_saidas_contas1`
    FOREIGN KEY (`conta`)
    REFERENCES `smartchurch`.`contas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_saidas_subcategorias1`
    FOREIGN KEY (`subcategoria`)
    REFERENCES `smartchurch`.`subcategorias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`secretarias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`secretarias` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`secretarias` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `logo` VARCHAR(256) NULL DEFAULT NULL COMMENT 'path da imagem de logo',
  `email` VARCHAR(256) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `ramal` VARCHAR(20) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`secretarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`secretarios` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`secretarios` (
  `id` CHAR(24) NOT NULL,
  `secretaria` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `perfil` CHAR(24) NOT NULL,
  `tipo` CHAR(1) NULL DEFAULT NULL COMMENT 'marca se eh auxiliar do secretario',
  `data_admissao` DATE NULL,
  `data_demissao` DATE NULL,
  `stat` CHAR(3) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_secretarios_secretarias1_idx` (`secretaria` ASC) VISIBLE,
  INDEX `fk_secretarios_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  INDEX `fk_secretarios_perfis1_idx` (`perfil` ASC) VISIBLE,
  CONSTRAINT `fk_secretarios_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_secretarios_secretarias1`
    FOREIGN KEY (`secretaria`)
    REFERENCES `smartchurch`.`secretarias` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_secretarios_perfis1`
    FOREIGN KEY (`perfil`)
    REFERENCES `smartchurch`.`perfis` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`series_sermoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`series_sermoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`series_sermoes` (
  `id` CHAR(24) NOT NULL,
  `igreja` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `chave` VARCHAR(256) NULL DEFAULT NULL,
  `logo` VARCHAR(256) NULL DEFAULT NULL,
  `inicio` DATE NULL,
  `termino` DATE NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_series_sermoes_igrejas1_idx` (`igreja` ASC) VISIBLE,
  CONSTRAINT `fk_series_sermoes_igrejas1`
    FOREIGN KEY (`igreja`)
    REFERENCES `smartchurch`.`igrejas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`sermoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`sermoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`sermoes` (
  `id` CHAR(24) NOT NULL,
  `igreja` CHAR(24) NOT NULL,
  `serie` CHAR(24) NULL DEFAULT NULL,
  `autor` CHAR(24) NULL DEFAULT NULL,
  `titulo` VARCHAR(150) NULL DEFAULT NULL,
  `chave` VARCHAR(256) NULL DEFAULT NULL,
  `logo` VARCHAR(256) NULL DEFAULT NULL,
  `logo_app` VARCHAR(256) NULL,
  `data_sermao` DATE NULL DEFAULT NULL,
  `conteudo` TEXT NULL DEFAULT NULL,
  `anexo` VARCHAR(256) NULL DEFAULT NULL,
  `video` VARCHAR(256) NULL DEFAULT NULL,
  `audio` TEXT NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sermoes_igrejas1_idx` (`igreja` ASC) VISIBLE,
  INDEX `autor_indx` USING BTREE (`autor`) VISIBLE,
  INDEX `fk_sermoes_series_sermoes1_idx` (`serie` ASC) VISIBLE,
  CONSTRAINT `fk_sermoes_igrejas1`
    FOREIGN KEY (`igreja`)
    REFERENCES `smartchurch`.`igrejas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sermoes_series_sermoes1`
    FOREIGN KEY (`serie`)
    REFERENCES `smartchurch`.`series_sermoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`servos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`servos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`servos` (
  `id` CHAR(24) NOT NULL,
  `ministerio` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `data_admissao` DATE NULL,
  `data_demissao` DATE NULL,
  `admin` CHAR(1) NULL,
  `stat` CHAR(3) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_servos_ministerios1_idx` (`ministerio` ASC) VISIBLE,
  INDEX `fk_servos_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_servos_ministerios1`
    FOREIGN KEY (`ministerio`)
    REFERENCES `smartchurch`.`ministerios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_servos_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`sites`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`sites` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`sites` (
  `id` CHAR(24) NOT NULL,
  `site` VARCHAR(256) NULL DEFAULT NULL,
  `facebook` VARCHAR(256) NULL DEFAULT NULL,
  `instagram` VARCHAR(256) NULL DEFAULT NULL,
  `youtube` VARCHAR(256) NULL DEFAULT NULL,
  `vimeo` VARCHAR(256) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'link externos e redes sociais de pessoas, instancias, igrejas';


-- -----------------------------------------------------
-- Table `smartchurch`.`sociedades`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`sociedades` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`sociedades` (
  `id` CHAR(24) NOT NULL,
  `igreja` CHAR(24) NOT NULL,
  `federacao` CHAR(24) NULL DEFAULT NULL,
  `sinodal` CHAR(24) NULL DEFAULT NULL,
  `nacional` CHAR(24) NULL DEFAULT NULL,
  `reference` CHAR(3) NULL DEFAULT NULL COMMENT 'ump, saf, etc',
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `logo` VARCHAR(256) NULL DEFAULT NULL,
  `fundacao` DATE NULL DEFAULT NULL,
  `email` VARCHAR(256) NULL DEFAULT NULL,
  `telefone` VARCHAR(20) NULL DEFAULT NULL,
  `ramal` VARCHAR(20) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_sociedades_igrejas1_idx` (`igreja` ASC) VISIBLE,
  INDEX `fk_sociedades_federacoes1_idx` (`federacao` ASC) VISIBLE,
  INDEX `fk_sociedades_sinodais1_idx` (`sinodal` ASC) VISIBLE,
  INDEX `fk_sociedades_nacionais1_idx` (`nacional` ASC) VISIBLE,
  CONSTRAINT `fk_sociedades_federacoes1`
    FOREIGN KEY (`federacao`)
    REFERENCES `smartchurch`.`federacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sociedades_igrejas1`
    FOREIGN KEY (`igreja`)
    REFERENCES `smartchurch`.`igrejas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sociedades_nacionais1`
    FOREIGN KEY (`nacional`)
    REFERENCES `smartchurch`.`nacionais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sociedades_sinodais1`
    FOREIGN KEY (`sinodal`)
    REFERENCES `smartchurch`.`sinodais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`socios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`socios` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`socios` (
  `id` CHAR(24) NOT NULL,
  `sociedade` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `data_admissao` DATE NULL DEFAULT NULL,
  `data_demissao` DATE NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `admin` CHAR(1) NULL,
  `diretoria` CHAR(1) NULL DEFAULT NULL,
  `cooperador` CHAR(1) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_socios_sociedades1_idx` (`sociedade` ASC) VISIBLE,
  INDEX `fk_socios_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_socios_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_socios_sociedades1`
    FOREIGN KEY (`sociedade`)
    REFERENCES `smartchurch`.`sociedades` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`sysconfigs`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`sysconfigs` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`sysconfigs` (
  `id` CHAR(24) NOT NULL,
  `perfil_membro` CHAR(24) NULL DEFAULT NULL COMMENT 'id do perfil padrao de membresia',
  `perfil_cliente` CHAR(24) NULL DEFAULT NULL COMMENT 'perfil padrao de cliente',
  `perfil_diretoria_sociedade` CHAR(24) NULL DEFAULT NULL COMMENT 'perfil padrao de diretoria de sociedade interna',
  `perfil_federacao` CHAR(24) NULL DEFAULT NULL,
  `perfil_sinodal` CHAR(24) NULL DEFAULT NULL,
  `perfil_superintendente` CHAR(24) NULL,
  `perfil_secretario` CHAR(24) NULL,
  `perfil_ministerio` CHAR(24) NULL,
  `perfil_pastor` CHAR(24) NULL,
  `perfil_evangelista` CHAR(24) NULL,
  `perfil_presbitero` CHAR(24) NULL,
  `perfil_diacono` CHAR(24) NULL,
  `perfil_referencia` CHAR(24) NULL COMMENT 'perfil padrao para login via referencia na api',
  `perfil_professor` CHAR(24) NULL,
  `tag_evento` CHAR(24) NULL,
  `tag_eleicao` CHAR(24) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'configuracoes do sistema';


-- -----------------------------------------------------
-- Table `smartchurch`.`tags`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`tags` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`tags` (
  `id` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `nome` VARCHAR(150) NULL DEFAULT NULL,
  `cor` VARCHAR(45) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`tags_agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`tags_agenda` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`tags_agenda` (
  `id` CHAR(24) NOT NULL,
  `tag` VARCHAR(150) NULL DEFAULT NULL,
  `cor` VARCHAR(20) NULL DEFAULT NULL,
  `contextos` TEXT NULL COMMENT 'contextos da tag: pastor, conselho, sociedade interna, etc',
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`tags_da_agenda`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`tags_da_agenda` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`tags_da_agenda` (
  `agenda` CHAR(24) NOT NULL,
  `tag` CHAR(24) NOT NULL,
  PRIMARY KEY (`agenda`, `tag`),
  INDEX `fk_agendas_has_tags_agenda_tags_agenda1_idx` (`tag` ASC) VISIBLE,
  INDEX `fk_agendas_has_tags_agenda_agendas1_idx` (`agenda` ASC) VISIBLE,
  CONSTRAINT `fk_agendas_has_tags_agenda_agendas1`
    FOREIGN KEY (`agenda`)
    REFERENCES `smartchurch`.`agendas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_agendas_has_tags_agenda_tags_agenda1`
    FOREIGN KEY (`tag`)
    REFERENCES `smartchurch`.`tags_agenda` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`tags_da_entrada`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`tags_da_entrada` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`tags_da_entrada` (
  `tag` CHAR(24) NOT NULL,
  `entrada` CHAR(24) NOT NULL,
  PRIMARY KEY (`tag`, `entrada`),
  INDEX `fk_entradas_has_tags_tags1_idx` (`tag` ASC) VISIBLE,
  INDEX `fk_entradas_has_tags_entradas1_idx` (`entrada` ASC) VISIBLE,
  CONSTRAINT `fk_entradas_has_tags_entradas1`
    FOREIGN KEY (`entrada`)
    REFERENCES `smartchurch`.`entradas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_entradas_has_tags_tags1`
    FOREIGN KEY (`tag`)
    REFERENCES `smartchurch`.`tags` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`tags_da_saida`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`tags_da_saida` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`tags_da_saida` (
  `tag` CHAR(24) NOT NULL,
  `saida` CHAR(24) NOT NULL,
  PRIMARY KEY (`tag`, `saida`),
  INDEX `fk_tags_has_saidas_saidas1_idx` (`saida` ASC) VISIBLE,
  INDEX `fk_tags_has_saidas_tags1_idx` (`tag` ASC) VISIBLE,
  CONSTRAINT `fk_tags_has_saidas_saidas1`
    FOREIGN KEY (`saida`)
    REFERENCES `smartchurch`.`saidas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_tags_has_saidas_tags1`
    FOREIGN KEY (`tag`)
    REFERENCES `smartchurch`.`tags` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`transmissoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`transmissoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`transmissoes` (
  `id` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL DEFAULT NULL,
  `ref_tp` CHAR(3) NULL DEFAULT NULL,
  `video` VARCHAR(256) NULL DEFAULT NULL,
  `stat` CHAR(3) NULL DEFAULT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  `last_mod` DATETIME NULL DEFAULT NULL,
  `last_amod` VARCHAR(150) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'registra os links de transmissao ao vivo';


-- -----------------------------------------------------
-- Table `smartchurch`.`votantes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`votantes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`votantes` (
  `id` CHAR(24) NOT NULL,
  `votacao` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_votantes_votacoes1_idx` (`votacao` ASC) VISIBLE,
  INDEX `fk_votantes_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_votantes_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_votantes_votacoes1`
    FOREIGN KEY (`votacao`)
    REFERENCES `smartchurch`.`votacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'registro de quem votou ou nao numa votacao';


-- -----------------------------------------------------
-- Table `smartchurch`.`votos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`votos` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`votos` (
  `id` CHAR(24) NOT NULL,
  `eleicao` CHAR(24) NOT NULL,
  `votacao` CHAR(24) NOT NULL,
  `escrutinio` CHAR(24) NOT NULL,
  `candidato` CHAR(24) NOT NULL,
  `time_cad` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_votos_candidatos1_idx` (`candidato` ASC) VISIBLE,
  INDEX `fk_votos_escrutinios1_idx` (`escrutinio` ASC) VISIBLE,
  INDEX `fk_votos_votacoes1_idx` (`votacao` ASC) VISIBLE,
  INDEX `fk_votos_eleicoes1_idx` (`eleicao` ASC) VISIBLE,
  CONSTRAINT `fk_votos_candidatos1`
    FOREIGN KEY (`candidato`)
    REFERENCES `smartchurch`.`candidatos` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_votos_eleicoes1`
    FOREIGN KEY (`eleicao`)
    REFERENCES `smartchurch`.`eleicoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_votos_escrutinios1`
    FOREIGN KEY (`escrutinio`)
    REFERENCES `smartchurch`.`escrutinios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_votos_votacoes1`
    FOREIGN KEY (`votacao`)
    REFERENCES `smartchurch`.`votacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `smartchurch`.`votos_ctrl`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`votos_ctrl` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`votos_ctrl` (
  `votacao` CHAR(24) NOT NULL,
  `escrutinio` CHAR(24) NOT NULL,
  `votante` CHAR(24) NOT NULL,
  PRIMARY KEY (`votacao`, `escrutinio`, `votante`),
  INDEX `fk_votos_ctrl_escrutinios1_idx` (`escrutinio` ASC) VISIBLE,
  INDEX `fk_votos_ctrl_votacoes1_idx` (`votacao` ASC) VISIBLE,
  INDEX `fk_votos_ctrl_votantes1` (`votante` ASC) VISIBLE,
  CONSTRAINT `fk_votos_ctrl_escrutinios1`
    FOREIGN KEY (`escrutinio`)
    REFERENCES `smartchurch`.`escrutinios` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_votos_ctrl_votacoes1`
    FOREIGN KEY (`votacao`)
    REFERENCES `smartchurch`.`votacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_votos_ctrl_votantes1`
    FOREIGN KEY (`votante`)
    REFERENCES `smartchurch`.`votantes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'controla quem votou na votacao e escrutinio';


-- -----------------------------------------------------
-- Table `smartchurch`.`doacoes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`doacoes` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`doacoes` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`doacoes_do_socio`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`doacoes_do_socio` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`doacoes_do_socio` (
  `id` CHAR(24) NOT NULL,
  `doacao` CHAR(24) NOT NULL,
  `socio` CHAR(24) NOT NULL,
  `data` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_doacoes_has_socios_socios1_idx` (`socio` ASC) VISIBLE,
  INDEX `fk_doacoes_has_socios_doacoes1_idx` (`doacao` ASC) VISIBLE,
  CONSTRAINT `fk_doacoes_doacao`
    FOREIGN KEY (`doacao`)
    REFERENCES `smartchurch`.`doacoes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_doacoes_socio`
    FOREIGN KEY (`socio`)
    REFERENCES `smartchurch`.`socios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`doadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`doadores` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`doadores` (
  `doacao` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  PRIMARY KEY (`doacao`, `pessoa`),
  INDEX `fk_doacoes_has_pessoas_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  INDEX `fk_doacoes_has_pessoas_doacoes1_idx` (`doacao` ASC) VISIBLE,
  CONSTRAINT `fk_doacoes_has_pessoas_doacoes1`
    FOREIGN KEY (`doacao`)
    REFERENCES `smartchurch`.`doacoes` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_doacoes_has_pessoas_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`necessidades_especiais`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`necessidades_especiais` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`necessidades_especiais` (
  `id` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`necessidades_das_pessoas`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`necessidades_das_pessoas` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`necessidades_das_pessoas` (
  `necessidade` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  PRIMARY KEY (`necessidade`, `pessoa`),
  INDEX `fk_necessidades_especiais_has_pessoas_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  INDEX `fk_necessidades_especiais_has_pessoas_necessidades_especiai_idx` (`necessidade` ASC) VISIBLE,
  CONSTRAINT `fk_necessidades_especiais_has_pessoas_necessidades_especiais1`
    FOREIGN KEY (`necessidade`)
    REFERENCES `smartchurch`.`necessidades_especiais` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_necessidades_especiais_has_pessoas_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`bookmarks`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`bookmarks` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`bookmarks` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL,
  `ref_tp` CHAR(3) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_bookmarks_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_bookmarks_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`mural`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`mural` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`mural` (
  `id` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL,
  `ref_tp` CHAR(3) NULL,
  `titulo` VARCHAR(150) NULL,
  `chave` VARCHAR(256) NULL,
  `img` VARCHAR(256) NULL,
  `conteudo` TEXT NULL,
  `video` VARCHAR(256) NULL,
  `audio` TEXT NULL,
  `destinatarios` TEXT NULL,
  `stat` CHAR(3) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`atualizacoes_sumarios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`atualizacoes_sumarios` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`atualizacoes_sumarios` (
  `id` CHAR(24) NOT NULL,
  `sala` CHAR(24) NOT NULL,
  `dia` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_atualizacoes_sumarios_salas_ebd1_idx` (`sala` ASC) VISIBLE,
  CONSTRAINT `fk_atualizacoes_sumarios_salas_ebd1`
    FOREIGN KEY (`sala`)
    REFERENCES `smartchurch`.`salas_ebd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`pedidos_oracao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`pedidos_oracao` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`pedidos_oracao` (
  `id` CHAR(24) NOT NULL,
  `autor` CHAR(24) NOT NULL,
  `ref` CHAR(24) NULL,
  `ref_tp` CHAR(3) NULL,
  `pedido` TEXT NULL,
  `stat` CHAR(3) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_pedidos_oracao_pessoas1_idx` (`autor` ASC) VISIBLE,
  CONSTRAINT `fk_pedidos_oracao_pessoas1`
    FOREIGN KEY (`autor`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`temas_ebd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`temas_ebd` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`temas_ebd` (
  `id` CHAR(24) NOT NULL,
  `sala` CHAR(24) NOT NULL,
  `nome` VARCHAR(150) NULL,
  `bibliografia` TEXT NULL,
  `stat` CHAR(3) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_temas_ebd_salas_ebd1_idx` (`sala` ASC) VISIBLE,
  CONSTRAINT `fk_temas_ebd_salas_ebd1`
    FOREIGN KEY (`sala`)
    REFERENCES `smartchurch`.`salas_ebd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`conteudos_ebd`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`conteudos_ebd` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`conteudos_ebd` (
  `id` CHAR(24) NOT NULL,
  `tema` CHAR(24) NOT NULL,
  `titulo` VARCHAR(150) NULL,
  `dia` DATE NULL,
  `conteudo` TEXT NULL,
  `anexo` VARCHAR(256) NULL,
  `video` VARCHAR(256) NULL,
  `audio` TEXT NULL,
  `stat` CHAR(3) NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_conteudos_ebd_temas_ebd1_idx` (`tema` ASC) VISIBLE,
  CONSTRAINT `fk_conteudos_ebd_temas_ebd1`
    FOREIGN KEY (`tema`)
    REFERENCES `smartchurch`.`temas_ebd` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `smartchurch`.`historico_membresia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `smartchurch`.`historico_membresia` ;

CREATE TABLE IF NOT EXISTS `smartchurch`.`historico_membresia` (
  `id` CHAR(24) NOT NULL,
  `pessoa` CHAR(24) NOT NULL,
  `igreja` VARCHAR(256) NULL,
  `pastor` VARCHAR(150) NULL,
  `telefone_pastor` VARCHAR(20) NULL,
  `email_pastor` VARCHAR(256) NULL,
  `membro` CHAR(1) NULL,
  `frequentou_de` DATE NULL,
  `frequentou_ate` DATE NULL,
  `comungante` CHAR(1) NULL,
  `batizado` CHAR(1) NULL,
  `data_batismo` DATE NULL,
  `time_cad` DATETIME NULL,
  `last_mod` DATETIME NULL,
  `last_amod` VARCHAR(150) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_historico_membresia_pessoas1_idx` (`pessoa` ASC) VISIBLE,
  CONSTRAINT `fk_historico_membresia_pessoas1`
    FOREIGN KEY (`pessoa`)
    REFERENCES `smartchurch`.`pessoas` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
